/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class neuralNetwork_NeuralNetworkWrapper */

#ifndef _Included_neuralNetwork_NeuralNetworkWrapper
#define _Included_neuralNetwork_NeuralNetworkWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     neuralNetwork_NeuralNetworkWrapper
 * Method:    createNeuralNetwork
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_neuralNetwork_NeuralNetworkWrapper_createNeuralNetwork
  (JNIEnv *, jobject);

/*
 * Class:     neuralNetwork_NeuralNetworkWrapper
 * Method:    copyNetwork
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_neuralNetwork_NeuralNetworkWrapper_copyNetwork
  (JNIEnv *, jobject, jlong);

/*
 * Class:     neuralNetwork_NeuralNetworkWrapper
 * Method:    destroyNeuralNetwork
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_neuralNetwork_NeuralNetworkWrapper_destroyNeuralNetwork
  (JNIEnv *, jobject, jlong);

/*
 * Class:     neuralNetwork_NeuralNetworkWrapper
 * Method:    setUpNetwork
 * Signature: (J[II)V
 */
JNIEXPORT void JNICALL Java_neuralNetwork_NeuralNetworkWrapper_setUpNetwork
  (JNIEnv *, jobject, jlong, jintArray, jint);

/*
 * Class:     neuralNetwork_NeuralNetworkWrapper
 * Method:    forwardPass
 * Signature: (J[D[DII)V
 */
JNIEXPORT void JNICALL Java_neuralNetwork_NeuralNetworkWrapper_forwardPass
  (JNIEnv *, jobject, jlong, jdoubleArray, jdoubleArray, jint, jint);

/*
 * Class:     neuralNetwork_NeuralNetworkWrapper
 * Method:    backPropagateRMS
 * Signature: (J[DI)V
 */
JNIEXPORT void JNICALL Java_neuralNetwork_NeuralNetworkWrapper_backPropagateRMS
  (JNIEnv *, jobject, jlong, jdoubleArray, jint);

/*
 * Class:     neuralNetwork_NeuralNetworkWrapper
 * Method:    backPropagate
 * Signature: (J[DI)V
 */
JNIEXPORT void JNICALL Java_neuralNetwork_NeuralNetworkWrapper_backPropagate
  (JNIEnv *, jobject, jlong, jdoubleArray, jint);

#ifdef __cplusplus
}
#endif
#endif
